name: Exceed concurrency 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  wait01:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait02:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait03:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait04:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait05:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait06:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait07:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait08:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait09:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait10:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait11:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait12:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait13:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait14:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait15:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait16:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait17:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait18:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait19:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait20:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait21:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait22:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait23:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait24:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait25:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait26:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait27:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait28:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
  wait29:
    uses: h2flohtest2/workflow/.github/workflows/waiting.yml@main
